#³¢®Ë¸Û ¸ê¤u¤T 406410114
SHELL = /bin/bash
CC = javac
CC1 = jar

main: Computer_Assisted_multiplicatio.java
	${CC} Computer_Assisted_multiplicatio.java
	${CC1} cfe myJar.jar Computer_Assisted_multiplicatio Computer_Assisted_multiplicatio.class

clean:
	rm *.class