#³¢®Ë¸Û ¸ê¤u¤T 406410114
#javac Java_HW4_*.java
#jar cfe myJar.jar Java_HW4_BouncingBalls Java_HW4_*.class
#
SHELL = /bin/bash
CC = javac
CC1 = jar

main:  Java_HW4_BouncingBalls.java
	${CC} Java_HW4_*.java
	${CC1} cfe myJar.jar Java_HW4_BouncingBalls Java_HW4_*.class
 
clean:
	rm -f Java_HW4_*.class
