#³¢®Ë¸Û ¸ê¤u¤T 406410114
SHELL = /bin/bash
CC = javac
CC1 = jar

main: Java_HW2.java
	${CC} Java_HW2.java Bicycle.java Building.java Car.java CarbonFootprint.java
	${CC1} cfe myJar.jar Java_HW2 Java_HW2.class Bicycle.class Building.class Car.class CarbonFootprint.class

clean:
	rm *.class